### ISSUE TITLE
Where is settings.ini on Mac?

### ISSUE THREAD

**Issue by vinbrule** [hyun-yang/MyChatGPT#1]
hello, could you help me to find settings.ini on mac? where is it?

**Comment by hyun-yang** [comment]
If you run python main.py, 
settings.ini and mychatgpt.db will be created in the same folder.
![settings ini folder](https://github.com/user-attachments/assets/772f7962-d043-4269-a524-b29cf2870760)

**Comment by vinbrule** [comment]
thank you
